from commands import *


def myprint(text):
    print(text)
    if story:
        t.sleep(len(text)*0.05)


def story_pause():
    while True:
        player_info()
        print("1 -open inventory")
        print("2 -rest (refill some health)")
        print("3 -continue story")
        action = myinput([1, 2, 3, "cheat"])
        if action == 3:
            if round(P.inventory_used, 1) <= P.inventory_capacity:
                clear_console()
                return
            else:
                print("you carry too much items")
        elif action == 1:
            open_inventory()
        elif action == 2:
            pass_time(10)
            print("you rested for 10 minutes")
            t.sleep(game_speed)


def get_items(items):
    for item in items:
        get_item(item)


print("Pyzombies")
t.sleep(1)
print("made by David Sobek")
t.sleep(1)
World.time = 60*8
game_setup()
story = True


P.hunger = 50
myprint("It was day like any other.")
myprint("You were sleeping comfortably in your bed.")
myprint("Suddenly you hear someone in the next room.")
myprint("You live alone, so you take your pocket knife and go investigate.")
P.weapons[0] = c.deepcopy(pocket_knife)
myprint("You slowly open the door and...")
myprint("Suddenly you get attacked by someone.")
P.health -= 30
clear_console()
print("-- battle tutorial --")
print("this game is designed to be played on numeric keyboard")
print("you can do 3 actions each round")
print("press 1/2/3 to select weapon")
print("different weapons have different stats (damage, range, durability, stamina cost...)")
print("press 0 to defend - converts all remaining actions to armor")
print("press + to open inventory")
print("press enter to rest - converts all remaining actions to stamina")
print("enemies will get closer every round and attack you if they can")
input("press enter to start")
fight(random_enemies=False, enemy_pool=[zombie])
clear_console()
myprint("You managed to defeat him, but something is strange.")
myprint("He didn't act like normal human.")
myprint("He was acting more like zombie...")
myprint("You should heal your wounds.")
myprint("You remember you had a medkit somewhere in the kitchen.")
get_item(medkit)
clear_console()
print("-- inventory tutorial --")
print("all items and weapons that aren't currently equiped are stored in your inventory")
print("each item has weight, if you carry too much items you won't be able to travel")
print("enter item name to select it")
print("enter 0 to close it")
open_inventory()
clear_console()
myprint("You decide to check on your neighbours.")
pass_time(5)
myprint("When you look into their house through window you can see 2 rotten creatures.")
myprint("You pick up wooden plank from the ground and head inside.")
P.weapons[1] = plank
myprint("When they see you enter the house, they both attack.")
fight(random_enemies=False, enemy_pool=[zombie, rotten_zombie])
clear_console()
myprint("You have to find out what is happening.")
myprint("When you turn on the TV you can see emergency message.")
myprint("Virus from secret laboratory escaped and turns people into zombies.")
myprint("If you get bitten you have around 6 hours before you turn into zombie!")
myprint("There is supposed to be cure somewhere in the laboratory, but no one got there since the outbreak.")
myprint("You already got bit, so you decide that you have nothing to loose if you try to get it.")
myprint("you should get some supplies from the nearby supermarket first.")
myprint("You take some food and medical supplies and head there.")
get_items([medkit, bandage, apple])
myprint("- you can use bandages to stop bleeding")
story_pause()
pass_time(10)
myprint("You can see 2 enemies in front part of the shop.")
fight(random_enemies=False, enemy_pool=[zombie, runner])
clear_console()
myprint("That zombie was faster than the others.")
myprint("It seems that the virus is mutating.")
myprint("You explore front part of the shop.")
get_items([bread, meat, medkit, medkit, hamburger, pipe, bow, arrows])
myprint("To get to the laboratory you have to go through dark forest.")
myprint("You should prepare before you go.")
myprint("- go to your inventory to equip new weapons")
myprint("- ranged weapons have to be loaded with ammo")
story_pause()
clear_console()
pass_time(60)
myprint("After around hour of walking you get suddenly attacked by zombies.")
fight(random_enemies=False, enemy_pool=[zombie, runner, rotten_zombie])
clear_console()
get_item(berries)
story_pause()
pass_time(60)
myprint("You continue to walk until you stumble upon abandoned cabin.")
myprint("You could find some weapons inside")
fight(random_enemies=False, enemy_pool=[zombie, big_zombie])
clear_console()
myprint("You search the cabin but you didn't find much.")
get_items([axe, bandage, medkit, berries])
myprint("In the last drawer you find a piece of paper with a code.")
myprint("You decide to search if you can't find what is it for.")
myprint("When you look behind a painting you find a safe.")
myprint("Inside are weird pills, ID card and a handgun.")
myprint("It seems that the pills are one of the things that the secret laboratory was researching.")
get_items([handgun, ammo_7mm, ammo_7mm, blue_pill, green_pill])
story_pause()
myprint("You are preparing to leave, when suddenly a long entity enters the cabin")
fight(random_enemies=False, enemy_pool=[slender_zombie])
clear_console()
myprint("You kill the zombie but you can hear more are coming.")
fight(random_enemies=False, enemy_pool=[runner, runner, sprinter])
clear_console()
myprint("You should get going before more of them come.")
story_pause()
pass_time(60)
myprint("You arrive to the place where the lab should be")
myprint("You use the ID card to get inside but several zombies are blocking your path.")
fight(random_enemies=False, enemy_pool=[armored_zombie, spitter])
clear_console()
myprint("It looks like this place is whole infected.")
myprint("You head to the armory to get more weapons")
get_items([shotgun, ammo_shotgun, rifle, ammo_7mm, fire_axe, machete, medkit, morphine, bandage, MRE_pack, red_pill])
story_pause()
myprint("You head to genetics laboratory.")
myprint("On your way you meet more zombies")
fight(random_enemies=False, enemy_pool=[big_zombie, armored_zombie, spitter, runner])
clear_console()
myprint("You arrived to the genetics laboratory.")
myprint("You can hear something big inside.")
myprint("This is probably your last chance to prepare.")
story_pause()
myprint("You take a deep breath and go inside.")
fight(random_enemies=False, enemy_pool=[zombie, spitter, sprinter, giant_zombie])
myprint("After you defeated that monster you search the laboratory.")
myprint("You found the cure, but what are you going to do next?")
print("End of the chapter I.")
input()